[package]
name = "rwebapi"
version = "0.1.0"
authors = ["Hien Pham <hienduyph@gmail.com>"]
edition = "2021"

[dependencies]
actix-web = "4.4.0"
actix-cors = "0.6.4"
actix-files = "0.6.2"
actix-identity = "0.6.0"
actix-redis = "0.13.0"
actix-threadpool = "0.3.3"

tonic = { version = "0.10.2", features = ["tls"] }
prost = "0.12.1"
tower = "0.4.13"
prost-types = "0.12.1"

warp = "0.3.6"

axum = "0.6.20"

rand = "0.8.5"
serde = "1.0.189"
serde_derive = "1.0.189"
serde_json = "1.0.107"
chrono = { version = "0.4.31", features = ["serde"] }
uuid = { version = "1.5.0", features = ["serde", "v4"] }
argon2rs = "0.2.5"
derive_more = "0.99.17"
dotenv = "0.15.0"
envy = "0.4.2"
env_logger = "0.10.0"
jsonwebtoken = "9.1.0"
lazy_static = "1.4.0"
listenfd = "1.0.1"
log = "0.4.20"
rayon = "1.8.0"
redis-async = "0.16.1"
validator = "0.16.1"
validator_derive = "0.16.0"

tokio = { version = "1.33.0", features = ["rt-multi-thread", "time", "fs", "macros", "net"] }
futures = { version = "0.3.28", default-features = false, features = ["alloc"] }
tokio-stream = { version = "0.1.14", features = ["net"] }
async-stream = "0.3.5"
async-trait = "0.1.74"

diesel = { version = "2.1.3", features = ["chrono", "mysql", "postgres", "sqlite", "r2d2"] }
r2d2 = "0.8.10"

sqlx = { version = "0.7.2", features = [ "runtime-tokio-rustls" , "postgres", "chrono", "migrate", "uuid", "json"], default-features = false }
sea-orm = { version = "0.12.4", features = [ "sqlx-postgres", "runtime-tokio-rustls", "macros", "debug-print", "with-chrono" ], default-features = false }

[build-dependencies]
tonic-build = { version = "0.10.2", features = ["prost"] }

[dev-dependencies]
actix-http-test = "3.1.0"

[features]
sqlite = []
default = ["sqlite"]
