[package]
name = "rwebapi"
version = "0.1.0"
authors = ["Hien Pham <hienduyph@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "3.3.3"
actix-cors = "0.5.4"
actix-files = "0.5.0"
actix-identity = "0.3.1"
actix-redis = "0.9.2"
actix-threadpool = "0.3.3"
# let use the version locked in actix-web core
actix-service = "*"

tonic = { version = "0.6.2", features = ["tls"] }
prost = "0.9.0"
tower = "0.4.11"
prost-types = "0.9.0"

warp = "0.3.2"

rand = "0.8.4"
serde = "1.0.132"
serde_derive = "1.0.132"
serde_json = "1.0.73"
chrono = { version = "0.4.19", features = ["serde"] }
uuid = { version = "0.8.2", features = ["serde", "v4"] }
argon2rs = "0.2.5"
derive_more = "0.99.17"
dotenv = "0.15.0"
envy = "0.4.2"
env_logger = "0.9.0"
jsonwebtoken = "7.2.0"
lazy_static = "1.4.0"
listenfd = "0.3.5"
log = "0.4.14"
rayon = "1.5.1"
redis-async = "0.12.0"
validator = "0.14.0"
validator_derive = "0.14.0"

tokio = { version = "1.15.0", features = ["rt-multi-thread", "time", "fs", "macros", "net"] }
futures = { version = "0.3.19", default-features = false, features = ["alloc"] }
tokio-stream = { version = "0.1.8", features = ["net"] }
async-stream = "0.3.2"
async-trait = "0.1.52"

diesel = { version = "1.4.8", features = ["chrono", "mysql", "postgres", "sqlite", "r2d2", "uuidv07"] }
r2d2 = "0.8.9"

[build-dependencies]
tonic-build = { version = "0.6.2", features = ["prost"] }

[dev-dependencies]
actix-http-test = "2.1.0"

[features]
sqlite = []
default = ["sqlite"]
