[package]
name = "rwebapi"
version = "0.1.0"
authors = ["Hien Pham <hienduyph@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "4.2.1"
actix-cors = "0.6.4"
actix-files = "0.6.2"
actix-identity = "0.5.2"
actix-redis = "0.12.0"
actix-threadpool = "0.3.3"

tonic = { version = "0.8.3", features = ["tls"] }
prost = "0.11.3"
tower = "0.4.13"
prost-types = "0.11.2"

warp = "0.3.3"

rand = "0.8.5"
serde = "1.0.148"
serde_derive = "1.0.148"
serde_json = "1.0.89"
chrono = { version = "0.4.23", features = ["serde"] }
uuid = { version = "1.2.2", features = ["serde", "v4"] }
argon2rs = "0.2.5"
derive_more = "0.99.17"
dotenv = "0.15.0"
envy = "0.4.2"
env_logger = "0.10.0"
jsonwebtoken = "8.1.1"
lazy_static = "1.4.0"
listenfd = "1.0.0"
log = "0.4.17"
rayon = "1.6.0"
redis-async = "0.13.0"
validator = "0.16.0"
validator_derive = "0.16.0"

tokio = { version = "1.22.0", features = ["rt-multi-thread", "time", "fs", "macros", "net"] }
futures = { version = "0.3.25", default-features = false, features = ["alloc"] }
tokio-stream = { version = "0.1.11", features = ["net"] }
async-stream = "0.3.3"
async-trait = "0.1.59"

diesel = { version = "2.0.2", features = ["chrono", "mysql", "postgres", "sqlite", "r2d2"] }
r2d2 = "0.8.10"

[build-dependencies]
tonic-build = { version = "0.8.4", features = ["prost"] }

[dev-dependencies]
actix-http-test = "3.0.0"

[features]
sqlite = []
default = ["sqlite"]
