services:
  app:
    build: .
    container_name: rust_app
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/mydb"
    ports:
      - "8000:8000" 
    restart: unless-stopped

  db:
    image: docker.io/postgres:17-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "127.0.0.1:5432:5432"  # Expose if needed
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z,rw
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
 
