CREATE TABLE users (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  password VARCHAR(122) NOT NULL,
  created_by VARCHAR(36) NOT NULL,
  updated_by VARCHAR(36) NOT NULL,
  created_at Timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at Timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

